module.exports = {
    // 文本框（只读，可读写）
    DOMTYPE_TXT: 'DOMTYPE_TXT',
    // 直线
    DOMTYPE_LINE: 'DOMTYPE_LINE',
    // 简单形状
    DOMTYPE_SIMPLESHAPE: 'DOMTYPE_SIMPLESHAPE',
    // 自定SVG
    DOMTYPE_SVG: 'DOMTYPE_SVG',
    // 图标文本
    DOMTYPE_ICON: 'DOMTYPE_ICON',
    // 图片（）
    DOMTYPE_IMAGE: 'DOMTYPE_IMAGE',
    // 仪表盘
    DOMTYPE_ECHARTSGAUGE: 'DOMTYPE_ECHARTSGAUGE',
    // 折線圖
    DOMTYPE_ECHARTSLINE: 'DOMTYPE_ECHARTSLINE'

};

